workspace 'Unknown3DWorkspace.xcworkspace'

project 'Demo/Demo.xcodeproj'

# Demo工程需要
target 'Demo' do
    platform :ios, '8.0'
    project 'Demo/Demo.xcodeproj'
end

# SDK工程需要
target 'Unknown3D' do
    platform :ios, '8.0'
    project 'Unknown3D/Unknown3D.xcodeproj'
end
